//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLAsientos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientoContable
    {
        public int Id { get; set; }
        public int NoAsiento { get; set; }
        public string DescripcionAsiento { get; set; }
        public System.DateTime FechaAsiento { get; set; }
        public XMLAsientos.xsd4.TipoMovimiento TipoMovimiento { get; set; }
        public decimal Monto { get; set; }
        public string CuentaContable { get; set; }
    }
}
